language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# This will run on Travis' 'new' container-based infrastructure
sudo: true

notifications:
  email: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: mkRPG
    - GH_REPO_REF: github.com/mkRPGDev/mkRPG.git

#install pygame
install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

# Install dependencies
addons:
  apt:
    packages:
    #  - texlive-full
      - doxygen
      - doxygen-doc
    #  - doxygen-latex
    #  - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR
  - python3 -m unittest discover -v -s pytest -p "*.py"

# Generate and deploy documentation
#after_success:
  #- cd $TRAVIS_BUILD_DIR
  #- chmod +x generateDocumentation.sh
  #- ./generateDocumentation.sh
