language: python
python:
  - "3.5"

sudo: true

notifications:
  email:
    recipients:
      - jules.kozolinsky@ens-cachan.fr
      - pjeanmai@ens-cachan.fr
      - guinness@crans.org
      - clement.pascutto@ens.fr
      - ismail.lahkim.bennani@gmail.com
      - marc.coudriau@ens.fr
      - baptiste.pauget@ens.fr
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

# Blacklist
branches:
  except:
    - gh-pages

before_install:
    - sudo apt-get build-dep -y python-pygame
    - pip install hg+http://bitbucket.org/pygame/pygame
    - python -c "import pygame"

install:
    - pip3 install -r travis/test-requirements.txt

# Install dependencies
addons:
  apt:
    packages:
    #  - texlive-full
      - doxygen
      - doxygen-doc
    #  - doxygen-latex
    #  - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR
  - cd src/
  - python3 -m unittest discover -v


# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x travis/checkout_ghpages_script.sh
  - ./travis/checkout_ghpages_script.sh
